import Header from "@/components/Header";
import { getAdminLeaderboard } from "@/lib/admin-api";

export const revalidate = 0;
export const dynamic = "force-dynamic";

export default async function LeaderboardPage() {
  const leaderboard = await getAdminLeaderboard();

  return (
    <>
      <Header showNav />
      <main className="page-shell space-y-6">
        <section className="surface-card p-6 sm:p-7">
          <div className="flex items-center gap-2">
            <span className="pill-chip">Performance Index</span>
            <span className="font-mono text-xs text-zinc-400">
              {leaderboard.length} PR Members
            </span>
          </div>
          <h1 className="page-title mt-2">PR Referral Leaderboard</h1>
          <p className="page-subtitle">
            Live attribution rankings tracking validated registrations generated by PR team referral codes.
          </p>
        </section>

        <section className="surface-card p-5 sm:p-6 space-y-4">
          <div className="flex items-center justify-between border-b border-zinc-100 pb-3">
            <h2 className="text-xs font-semibold uppercase tracking-wider text-zinc-900">
              Team Attribution Standings
            </h2>
          </div>

          <div className="overflow-x-auto rounded-lg border border-zinc-200">
            <table className="w-full text-left text-xs">
              <thead className="border-b border-zinc-200 bg-zinc-50/80 text-[10px] font-mono uppercase tracking-wider text-zinc-400">
                <tr>
                  <th className="px-3.5 py-2.5 w-12">Rank</th>
                  <th className="px-3.5 py-2.5">Member Name</th>
                  <th className="px-3.5 py-2.5">Referral Code</th>
                  <th className="px-3.5 py-2.5 text-right">Confirmed Referrals</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-100 bg-white">
                {leaderboard.map((m, i) => (
                  <tr
                    key={m.code}
                    className="transition hover:bg-zinc-50/70"
                  >
                    <td className="px-3.5 py-3 font-mono font-bold">
                      {i === 0 ? (
                        <span className="flex h-5 w-5 items-center justify-center rounded bg-amber-100 text-amber-900 text-[10px]">1</span>
                      ) : i === 1 ? (
                        <span className="flex h-5 w-5 items-center justify-center rounded bg-zinc-200 text-zinc-800 text-[10px]">2</span>
                      ) : i === 2 ? (
                        <span className="flex h-5 w-5 items-center justify-center rounded bg-amber-50 text-amber-700 border border-amber-200 text-[10px]">3</span>
                      ) : (
                        <span className="text-zinc-400 pl-1">{i + 1}</span>
                      )}
                    </td>
                    <td className="px-3.5 py-3 font-medium text-zinc-900 font-sans">{m.name}</td>
                    <td className="px-3.5 py-3">
                      <span className="font-mono text-xs font-semibold text-brand-700 bg-brand-50 border border-brand-200/60 rounded px-1.5 py-0.5">
                        {m.code}
                      </span>
                    </td>
                    <td className="px-3.5 py-3 text-right font-mono font-bold text-zinc-900 text-sm">
                      {m.count}
                    </td>
                  </tr>
                ))}
                {leaderboard.length === 0 && (
                  <tr>
                    <td
                      colSpan={4}
                      className="px-4 py-8 text-center text-xs text-zinc-400 font-mono"
                    >
                      No referral data recorded yet.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </section>
      </main>
    </>
  );
}
