import {
  CheckCircle2,
  Clock,
  XCircle,
  Search,
  SlidersHorizontal,
  RefreshCw,
  Copy,
  Check,
  ExternalLink,
  Calendar,
  MapPin,
  Banknote,
  GitBranch,
  Tag,
  MoreHorizontal,
  X,
  ChevronLeft,
  ChevronRight,
  AlertTriangle,
  Info,
  ZoomIn,
  Eye,
  LogOut,
  ShieldCheck,
  Trophy,
  Inbox,
  BarChart2,
  ArrowUpRight,
  FileQuestion,
  Download,
  Ticket,
  Plus,
  Trash2,
  Edit,
  Key,
  ArrowRight,
  Settings,
} from "lucide-react";

export const STATUS_CONFIG = {
  approved: {
    icon: CheckCircle2,
    label: "Approved",
    badgeClass: "badge-approved",
    iconColor: "text-emerald-600",
  },
  pending: {
    icon: Clock,
    label: "Pending Review",
    badgeClass: "badge-pending",
    iconColor: "text-amber-600",
  },
  rejected: {
    icon: XCircle,
    label: "Rejected",
    badgeClass: "badge-rejected",
    iconColor: "text-rose-600",
  },
  needs_correction: {
    icon: AlertTriangle,
    label: "Needs Correction",
    badgeClass: "rounded font-mono text-[11px] font-semibold px-2 py-0.5 border border-amber-300 bg-amber-50 text-amber-800 inline-flex items-center gap-1",
    iconColor: "text-amber-600",
  },
  resubmitted: {
    icon: RefreshCw,
    label: "Resubmitted",
    badgeClass: "rounded font-mono text-[11px] font-semibold px-2 py-0.5 border border-indigo-300 bg-indigo-50 text-indigo-800 inline-flex items-center gap-1",
    iconColor: "text-indigo-600",
  },
  under_review: {
    icon: Eye,
    label: "Under Review",
    badgeClass: "rounded font-mono text-[11px] font-semibold px-2 py-0.5 border border-sky-300 bg-sky-50 text-sky-800 inline-flex items-center gap-1",
    iconColor: "text-sky-600",
  },
} as const;

export type RegistrationStatusType = keyof typeof STATUS_CONFIG;

export {
  CheckCircle2,
  Clock,
  XCircle,
  Search,
  SlidersHorizontal,
  RefreshCw,
  Copy,
  Check,
  ExternalLink,
  Calendar,
  MapPin,
  Banknote,
  GitBranch,
  Tag,
  MoreHorizontal,
  X,
  ChevronLeft,
  ChevronRight,
  AlertTriangle,
  Info,
  ZoomIn,
  Eye,
  LogOut,
  ShieldCheck,
  Trophy,
  Inbox,
  BarChart2,
  ArrowUpRight,
  FileQuestion,
  Download,
  Ticket,
  Plus,
  Trash2,
  Edit,
  Key,
  ArrowRight,
  Settings,
};
